#!/usr/bin/env node
// Generates shared/config.js from the SYNC_URL environment variable.
// Falls back to an empty string so widgets still work without sync.

const fs = require('fs');
const path = require('path');

const url = process.env.SYNC_URL || '';
const out = path.join(__dirname, '..', 'shared', 'config.js');

const content = `// Auto-generated by scripts/build-config.js — do not edit.\n// Set the SYNC_URL env var and re-run the build to update.\n\nvar SYNC_URL = ${JSON.stringify(url)};\n`;

fs.writeFileSync(out, content, 'utf8');
console.log(url
  ? `✓ shared/config.js written (SYNC_URL set)`
  : `✓ shared/config.js written (SYNC_URL empty — sync disabled)`
);
